sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t abevear/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abevear/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-143729985031"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"